frontend:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000

jwt:
  secret: mySuperSecureSecretKeyThatIsLongEnough123456789
  accessExpirationMs: 1800000
  refreshExpirationMs: 86400000
